name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: vitepress/yarn.json
      - run: cd vitepress && yarn install --frozen-lockfile
        name: Install

      - name: Build markdown
        run: node ./build.mjs

      - name: Build
        run: cd vitepress && yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: vitepress/docs/.vitepress/dist
